[tasks."schema:generate"]
description = "Generate Python models from the JSON schema."
run = [
  """
  uv run \
  --project src/private/app/factorio-cycle-calculator \
  --package factorio-cycle-calculator \
  --group dev \
  datamodel-codegen \
  --url https://raw.githubusercontent.com/jacquev6/factorio-data-raw-json-schema/refs/heads/main/factorio-data-raw-json-schema.full.json \
  --output src/factorio_cycle_calculator/generated/data_raw_models.py \
  --input-file-type jsonschema \
  --output-model-type dataclasses.dataclass \
  --target-python-version 3.12 \
  --formatters ruff-format""",
  """
  uv run \
  --project src/private/app/factorio-cycle-calculator \
  --package factorio-cycle-calculator \
  --group dev \
  ruff check \
  --fix \
  --exit-zero \
  --quiet \
  src/factorio_cycle_calculator/generated/data_raw_models.py""",
  """
  uv run \
  --project src/private/app/factorio-cycle-calculator \
  --package factorio-cycle-calculator \
  --group dev \
  ruff format \
  --quiet \
  src/factorio_cycle_calculator/generated/data_raw_models.py""",
]
outputs = ["src/factorio_cycle_calculator/generated/data_raw_models.py"]
