[build-system]
requires = ["hatchling>=1.24.2"]
build-backend = "hatchling.build"

[project]
name = "factorio-cycle-calculator"
version = "0.0.0-dev"
description = "Web calculator for Factorio production cycles."
readme = "README.md"
authors = [{ name = "Shuai Zhang", email = "zhangshuai.ustc@gmail.com" }]
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
classifiers = ["Private :: Do Not Upload"]
dependencies = ["ortools>=9.11.4210", "pillow>=10.3.0", "streamlit>=1.42.0"]

[project.scripts]
factorio-cycle-calculator = "factorio_cycle_calculator.__main__:main"

[dependency-groups]
dev = ["datamodel-code-generator[debug,ruff,http]>=0.53.0"]

[tool.hatch.build.targets.wheel]
packages = ["src/factorio_cycle_calculator"]

[tool.datamodel-codegen]
input = "https://raw.githubusercontent.com/jacquev6/factorio-data-raw-json-schema/refs/heads/main/factorio-data-raw-json-schema.full.json"
input-file-type = "jsonschema"
output = "src/factorio_cycle_calculator/generated/data_raw_models.py"
output-model-type = "dataclasses.dataclass"
target-python-version = "3.12"

[tool.ruff]
extend = "../../../../pyproject.toml"

[tool.ruff.lint.per-file-ignores]
"src/factorio_cycle_calculator/generated/data_raw_models.py" = ["D", "N815"]
