"""Read the smoke backend requirement and its native UV dependency closure."""

from __future__ import annotations

import re
import tomllib


def backend_version(content: bytes) -> str:
    """Require one exact stable Hatchling pin and the existing NBGV hook."""
    backend = tomllib.loads(content.decode("utf-8"))["build-system"]
    requirements = backend.get("requires")
    if (
        backend.get("build-backend") != "hatchling.build"
        or not isinstance(requirements, list)
        or requirements[1:] != ["nbgv-python"]
        or not isinstance(requirements[0], str)
        or not (
            match := re.fullmatch(
                r"hatchling==(\d+\.\d+\.\d+)", requirements[0]
            )
        )
    ):
        message = "Python smoke requires an exact Hatchling pin and NBGV hook"
        raise ValueError(message)
    return match[1]


def backend_constraints(lock_content: bytes, version: str) -> str:
    """Project the complete public-index backend closure with wheel hashes."""
    packages = tomllib.loads(lock_content.decode("utf-8")).get("package", [])
    pending = ["hatchling"]
    resolved = {}
    while pending:
        name = pending.pop()
        if name in resolved:
            continue
        candidates = [
            package for package in packages if package["name"] == name
        ]
        if len(candidates) != 1:
            message = (
                "Python backend lock closure is incomplete or ambiguous: "
                f"{name}"
            )
            raise ValueError(message)
        package = candidates[0]
        if package.get("source") != {"registry": "https://pypi.org/simple"}:
            message = "Python backend must resolve from the public PyPI index"
            raise ValueError(message)
        resolved[name] = package
        pending.extend(
            dependency["name"] for dependency in package.get("dependencies", [])
        )
    if resolved["hatchling"]["version"] != version:
        message = "Python backend manifest pin differs from the frozen UV lock"
        raise ValueError(message)
    lines = [
        (
            "# Generated by sync_python_build_backend.py "
            "from the manifest and UV lock."
        )
    ]
    for name, package in sorted(resolved.items()):
        hashes = sorted({wheel["hash"] for wheel in package.get("wheels", [])})
        if not hashes or any(
            not re.fullmatch(r"sha256:[0-9a-f]{64}", digest)
            for digest in hashes
        ):
            message = "Python backend lock lacks exact wheel hashes"
            raise ValueError(message)
        lines.append(
            f"{name}=={package['version']} "
            + " ".join("--hash=" + digest for digest in hashes)
        )
    return "\n".join(lines) + "\n"
