# Copyright 2015 Shuai Zhang
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    ignore:
      - dependency-name: '@types/node'
    schedule:
      interval: weekly
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch

  - package-ecosystem: bundler
    directory: /src/public/lib/asciidoctor-latexmath
    schedule:
      interval: weekly
    groups:
      ruby-asciidoctor-latexmath-minor:
        update-types:
          - minor
          - patch
      ruby-asciidoctor-latexmath-major:
        update-types:
          - major

  - package-ecosystem: bundler
    directory: /src/public/lib/hexo-renderer-asciidoc
    schedule:
      interval: weekly
    groups:
      ruby-hexo-renderer-asciidoc-minor:
        update-types:
          - minor
          - patch
      ruby-hexo-renderer-asciidoc-major:
        update-types:
          - major
