[tools]
# Runtimes
dotnet = "10"
go = "latest"
java = "lts"
node = "24"
python = "3"
ruby = "3.3"

# Package Managers
pnpm = "10"
uv = "latest"

# Utilities
"pipx:prek" = "latest"
pkl = "latest"

# Linters and Formatters
"go:github.com/B1NARY-GR0UP/nwa" = "latest"
taplo = "latest"
typos = "latest"
