<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <CurrentTargetFramework>net10.0</CurrentTargetFramework>
    <CurrentWpfTargetFramework>net10.0-windows</CurrentWpfTargetFramework>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ProduceReferenceAssembly Condition="'$(MSBuildProjectExtension)' == '.csproj'">true</ProduceReferenceAssembly>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile Condition="'$(RestorePackagesWithLockFile)' == '' and '$(MSBuildProjectExtension)' != '.proj'">true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(RestoreLockedMode)' == '' and ('$(TF_BUILD)' == 'true' or '$(ContinuousIntegrationBuild)' == 'true')">true</RestoreLockedMode>
    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
    <RestoreEnablePackagePruning>true</RestoreEnablePackagePruning>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <PropertyGroup Label="Code Analysis">
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <Sdk Name="DotNet.ReproducibleBuilds.Isolated" />
  <Sdk Name="Microsoft.Build.CopyOnWrite" />

  <PropertyGroup Label="SourceLink">
    <ProjectUrl>https://github.com/hcoona/three</ProjectUrl>
    <PackageProjectUrl>https://github.com/hcoona/three</PackageProjectUrl>
    <RepositoryUrl>https://github.com/hcoona/three.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup Label="CI" Condition="'$(ContinuousIntegrationBuild)' == 'true' or '$(TF_BUILD)' == 'true'">
    <DeterministicSourcePaths>true</DeterministicSourcePaths>
  </PropertyGroup>
</Project>
