packages:
  - src/public/lib/hexo-renderer-asciidoc
  - src/public/lib/steam-account-history-to-csv
  - src/private/app/im-acp-gateway/poc/*

linkWorkspacePackages: true

onlyBuiltDependencies:
  - hexo-util

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true
