packages:
  - src/public/hexo-renderer-asciidoc
  - src/public/steam-account-history-to-csv

linkWorkspacePackages: true

onlyBuiltDependencies:
  - hexo-util

saveWorkspaceProtocol: true

sharedWorkspaceLockfile: true
