<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <CurrentTargetFramework>net10.0</CurrentTargetFramework>

    <InvariantGlobalization>true</InvariantGlobalization>

    <Deterministic>true</Deterministic>

    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(TF_BUILD)' == 'true'">true</RestoreLockedMode>
    <RestorePackagesConfig>true</RestorePackagesConfig>
    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
    <RestoreEnablePackagePruning>true</RestoreEnablePackagePruning>

    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>

    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>

    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <Sdk Name="DotNet.ReproducibleBuilds.Isolated" />
  <Sdk Name="Microsoft.Build.CopyOnWrite" />

  <PropertyGroup Label="SourceLink">
    <PackageProjectUrl>https://github.com/hcoona/three</PackageProjectUrl>
    <RepositoryUrl>https://github.com/hcoona/three.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <GlobalPackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.39" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" />
  </ItemGroup>
</Project>
