<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)../'))" />

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.16" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="9.0.16" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.16" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Ini" Version="9.0.16" />
  </ItemGroup>
</Project>
