"""Workflow release contract validation and artifact naming helpers."""

from __future__ import annotations

from three_workflow_release_contracts.actions_artifacts import (
    ArtifactAdmission,
    ArtifactDownloadRequest,
    GitHubActionsArtifactMetadata,
    actions_download_artifact_inputs,
    admit_exactly_one_artifact,
    artifact_download_request,
    artifact_metadata_has_authoritative_producer_identity,
    artifact_zip_api_path,
    collect_artifacts_by_name,
    normalize_github_actions_artifact,
)
from three_workflow_release_contracts.artifact_names import (
    ArtifactNameInputs,
    artifact_name,
    github_release_asset_binding_json,
    immutable_binding_json,
    safe_id,
)
from three_workflow_release_contracts.ci_validation import (
    API_VERSIONS_BY_KIND,
    ARTIFACT_PHYSICAL_NAME_LENGTH,
    ARTIFACT_PHYSICAL_NAME_PREFIX,
    CANONICAL_JSON_PROFILE,
    DETAILS_BY_DIAGNOSTIC_CODE,
    DIGEST_ALGORITHM,
    REGISTERED_CI_VALIDATION_DIAGNOSTIC_CODES,
    REGISTERED_CI_VALIDATION_DIAGNOSTIC_DETAILS,
    REGISTERED_CI_VALIDATION_DIAGNOSTIC_FAMILIES,
    REGISTERED_CI_VALIDATION_KINDS,
    ArtifactPhysicalName,
    CiValidationKind,
    CommonEnvelope,
    DiagnosticDetail,
    DiagnosticFamily,
    DiagnosticSeverity,
    DiagnosticVerdictEffect,
    artifact_physical_name,
    artifact_physical_ref,
    canonical_json_bytes,
    canonical_json_digest,
    validate_artifact_logical_ref,
    validate_artifact_physical_name,
    validate_common_envelope,
)
from three_workflow_release_contracts.contracts import (
    REGISTERED_BUILD_DIAGNOSTIC_CODES,
    REGISTERED_DIAGNOSTIC_CODES,
    ContractValidationError,
    ValidationIssue,
    validate_contract,
)

__all__ = [
    "API_VERSIONS_BY_KIND",
    "ARTIFACT_PHYSICAL_NAME_LENGTH",
    "ARTIFACT_PHYSICAL_NAME_PREFIX",
    "CANONICAL_JSON_PROFILE",
    "DETAILS_BY_DIAGNOSTIC_CODE",
    "DIGEST_ALGORITHM",
    "REGISTERED_BUILD_DIAGNOSTIC_CODES",
    "REGISTERED_CI_VALIDATION_DIAGNOSTIC_CODES",
    "REGISTERED_CI_VALIDATION_DIAGNOSTIC_DETAILS",
    "REGISTERED_CI_VALIDATION_DIAGNOSTIC_FAMILIES",
    "REGISTERED_CI_VALIDATION_KINDS",
    "REGISTERED_DIAGNOSTIC_CODES",
    "ArtifactAdmission",
    "ArtifactDownloadRequest",
    "ArtifactNameInputs",
    "ArtifactPhysicalName",
    "CiValidationKind",
    "CommonEnvelope",
    "ContractValidationError",
    "DiagnosticDetail",
    "DiagnosticFamily",
    "DiagnosticSeverity",
    "DiagnosticVerdictEffect",
    "GitHubActionsArtifactMetadata",
    "ValidationIssue",
    "actions_download_artifact_inputs",
    "admit_exactly_one_artifact",
    "artifact_download_request",
    "artifact_metadata_has_authoritative_producer_identity",
    "artifact_name",
    "artifact_physical_name",
    "artifact_physical_ref",
    "artifact_zip_api_path",
    "canonical_json_bytes",
    "canonical_json_digest",
    "collect_artifacts_by_name",
    "github_release_asset_binding_json",
    "immutable_binding_json",
    "normalize_github_actions_artifact",
    "safe_id",
    "validate_artifact_logical_ref",
    "validate_artifact_physical_name",
    "validate_common_envelope",
    "validate_contract",
]
