<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <EnlistmentRoot>$(MSBuildThisFileDirectory.TrimEnd('\\'))</EnlistmentRoot>

    <CurrentTargetFramework>net10.0</CurrentTargetFramework>
    <CurrentWpfTargetFramework>net10.0-windows</CurrentWpfTargetFramework>

    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>

    <!-- https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization#invariant-mode -->
    <InvariantGlobalization>true</InvariantGlobalization>

    <ProduceReferenceAssembly Condition="'$(MSBuildProjectExtension)' == '.csproj'">true</ProduceReferenceAssembly>

    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreUseStaticGraphEvaluation>true</RestoreUseStaticGraphEvaluation>
    <RestoreEnablePackagePruning>true</RestoreEnablePackagePruning>

    <!-- https://devblogs.microsoft.com/nuget/introducing-central-package-management/ -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>

    <!-- Workaround: https://github.com/dotnet/sdk/issues/49917 -->
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <Sdk Name="DotNet.ReproducibleBuilds.Isolated" />
  <Sdk Name="Microsoft.Build.CopyOnWrite" />

  <PropertyGroup Label="Nerdbank.GitVersioning">
    <!--
    https://github.com/dotnet/Nerdbank.GitVersioning/blob/v3.5.119/doc/msbuild.md#reducing-getbuildversion-invocations -->
    <GitVersionBaseDirectory>$(MSBuildThisFileDirectory)</GitVersionBaseDirectory>
  </PropertyGroup>

  <PropertyGroup Label="SourceLink">
    <ProjectUrl>https://github.com/hcoona/three</ProjectUrl>
    <PackageProjectUrl>https://github.com/hcoona/three</PackageProjectUrl>
    <RepositoryUrl>https://github.com/hcoona/three.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup Label="CI" Condition="'$(ContinuousIntegrationBuild)'=='true'">
    <!-- Pipeline build must follow lock file instead of update them. -->
    <RestoreLockedMode>true</RestoreLockedMode>
    <DeterministicSourcePaths>true</DeterministicSourcePaths>
  </PropertyGroup>

  <Import Project="$(EnlistmentRoot)/stylecop.props" />

  <PropertyGroup Label="SlnGen">
    <SlnGenFolders>true</SlnGenFolders>
  </PropertyGroup>

  <ItemGroup Label="SlnGen">
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\.editorconfig" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\global.json" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\NuGet.Config" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\OneDotNet.ruleset" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\Directory.Build.props" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\Directory.Build.rsp" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\..\Directory.Packages.props" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\README.md" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\stylecop.json" />
    <SlnGenSolutionItem Include="$(EnlistmentRoot)\version.json" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.7.115" />
    <GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
  </ItemGroup>

  <PropertyGroup Label="NuPack">
    <!-- Only pack explicitly selected projects. -->
    <IsPackable>false</IsPackable>

    <Authors>Shuai Zhang</Authors>
    <Company>Shuai Zhang</Company>
    <Copyright>Copyright (c) Shuai Zhang 2025</Copyright>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <!-- Force to use portable to produce snupkg. -->
    <DebugType>portable</DebugType>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup Label="License">
    <None Include="$(EnlistmentRoot)\LICENSE" Pack="true" PackagePath="" />
    <None Include="$(EnlistmentRoot)\LICENSE.GPLv3.txt" Pack="true" PackagePath="" />
    <None Include="$(EnlistmentRoot)\LICENSE.LGPLv3-linking-exception.txt" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup Label="Artifacts">
    <UseArtifactsOutput>false</UseArtifactsOutput>
    <BaseArtifactsPath>$(EnlistmentRoot)\out</BaseArtifactsPath>

    <DefaultArtifactsFileMatch>$(DefaultArtifactsFileMatch) *.exe *.dll *.exe.config *.deps.json *.runtimeconfig.json</DefaultArtifactsFileMatch>
  </PropertyGroup>

  <PropertyGroup Label="Code Analysis">
    <!-- TODO(shuaizhang): update to 8.0 -->
    <AnalysisLevel>6.0</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <!-- CA2253: Temporarily. -->
    <!-- CA2254: https://stackoverflow.com/questions/70955861/the-logging-message-template-should-not-vary-between-calls-ca2254-when-only-pa -->
    <!-- NETSDK1187: Ignore until Test Framework fix it. -->
    <NoWarn>$(NoWarn);CA2253;CA2254;NETSDK1187</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
