<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <_GitVersionFileAbove>$([MSBuild]::GetPathOfFileAbove('version.json', '$(MSBuildProjectDirectory)'))</_GitVersionFileAbove>
    <GitVersionBaseDirectory Condition="'$(_GitVersionFileAbove)' != ''">$([MSBuild]::NormalizeDirectory($([System.IO.Path]::GetDirectoryName('$(_GitVersionFileAbove)'))))</GitVersionBaseDirectory>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
</Project>
