"""Project mise Python into uv, Actions and the installed V3 package."""

from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PACKAGE_RUNTIME = Path(
    "src/public/lib/three-workflow-delivery-v3/src/"
    "three_workflow_delivery_v3/_python_runtime.py"
)


def locked_python(root: Path) -> str:
    """Read one exact resolution and reject disagreement with its selector."""
    config = tomllib.loads((root / "mise.toml").read_text(encoding="utf-8"))
    lock = tomllib.loads((root / "mise.lock").read_text(encoding="utf-8"))
    entries = lock.get("tools", {}).get("python", [])
    if len(entries) != 1:
        message = "mise.lock must contain exactly one Python resolution"
        raise ValueError(message)
    version = entries[0]["version"]
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        message = "mise.lock Python version must be an exact stable version"
        raise ValueError(message)
    selector = config["tools"]["python"]
    if selector not in (version, version.rsplit(".", 1)[0]):
        message = f"mise Python selector {selector!r} disagrees with {version}"
        raise ValueError(message)
    return version


def synchronize(root: Path, *, write: bool = False) -> str:
    """Check projections by default; regenerate only on an explicit request."""
    version = locked_python(root)
    projections = {
        Path(".python-version"): version + "\n",
        PACKAGE_RUNTIME: (
            '"""Generated by sync_python_version.py; do not edit."""\n'
            "\n"
            f'PYTHON_VERSION = "{version}"\n'
        ),
    }
    for relative, content in projections.items():
        path = root / relative
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        elif not path.is_file() or path.read_text(encoding="utf-8") != content:
            message = (
                f"{relative} differs from mise.lock; "
                "run mise run sync:python-version"
            )
            raise ValueError(message)
    return version


def main() -> int:
    """Check or regenerate runtime projections without fetching tools."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    options = parser.parse_args()
    version = synchronize(ROOT, write=options.write)
    print(f"Python projections match mise {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
