"""Project the smoke manifest and UV lock into frozen Python build inputs."""

from __future__ import annotations

import argparse
import importlib.util
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PACKAGE = Path(
    "src/public/lib/three-workflow-delivery-v3/src/three_workflow_delivery_v3"
)
MANIFEST = Path("src/public/lib/hcoona-release-smoke-python/pyproject.toml")
CONSTRAINTS = Path("eng/workflow-delivery/v3/python-build-constraints.txt")
PROJECTION = PACKAGE / "_python_build_backend.py"

# Load the shared native reader without importing the installed V3 toolchain.
SPEC = importlib.util.spec_from_file_location(
    "python_backend", ROOT / PACKAGE / "repository/python_backend.py"
)
if SPEC is None or SPEC.loader is None:
    message = "Cannot load the Python backend reader"
    raise RuntimeError(message)
backend = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(backend)


def synchronize(
    root: Path, *, write: bool = False, update_lock: bool = False
) -> str:
    """Check projections, or explicitly resolve and regenerate the backend."""
    version = backend.backend_version((root / MANIFEST).read_bytes())
    if update_lock:
        if not write:
            message = "--update-lock requires --write"
            raise ValueError(message)
        subprocess.run(
            ("uv", "lock", "--upgrade-package", f"hatchling=={version}"),
            cwd=root,
            check=True,
        )
    projections = {
        CONSTRAINTS: backend.backend_constraints(
            (root / "uv.lock").read_bytes(), version
        ),
        PROJECTION: (
            '"""Generated by sync_python_build_backend.py; do not edit."""\n'
            "\n"
            f'HATCHLING_VERSION = "{version}"\n'
            'HATCHLING_REQUIREMENT = f"hatchling=={HATCHLING_VERSION}"\n'
        ),
    }
    for relative, content in projections.items():
        path = root / relative
        if write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        elif not path.is_file() or path.read_text(encoding="utf-8") != content:
            message = (
                f"{relative} differs from the Python backend inputs; "
                "run mise run update-uv-lock"
            )
            raise ValueError(message)
    return version


def main() -> int:
    """Maintain reviewed build inputs without ambient package imports."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--update-lock", action="store_true")
    options = parser.parse_args()
    version = synchronize(
        ROOT, write=options.write, update_lock=options.update_lock
    )
    print(f"Python build inputs match Hatchling {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
