<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>$(CurrentTargetFramework)</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(EnlistmentRoot)\srcs\private\app\OxfordDictExtractor\OxfordDictExtractor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="examples\*.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
