<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Microsoft.Build.Artifacts" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(CurrentTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <AssemblyName>document-translator</AssemblyName>
    <RootNamespace>Hcoona.DocumentTranslatorCli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Translation.Document" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hcoona.DocumentTranslatorCli.Tests" />
  </ItemGroup>
</Project>
