[project]
name = "transcribe"
version = "0.0.0-dev"
description = "This project will transcribe audio files using the OpenAI models."
readme = "README.md"
authors = [{ name = "Shuai Zhang", email = "zhangshuai.ustc@gmail.com" }]
requires-python = ">=3.13"
license = "GPL-3.0-or-later"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
  "audioop-lts>=0.2.1",
  "azure-identity>=1.23.0",
  "openai>=1.77.0",
  "pydub>=0.25.1",
  "python-dotenv>=1.1.0",
]
