<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>hcoona-release-smoke-dotnet-executable</AssemblyName>
    <NoWarn>$(NoWarn);SA1633</NoWarn>
  </PropertyGroup>
</Project>
