<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net462;net8.0;net9.0</TargetFrameworks>

    <Nullable Condition="'$(TargetFramework)' != 'netstandard2.0' AND '$(TargetFramework)' != 'net462'">enable</Nullable>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">false</IsAotCompatible>

    <PackageId>WebHdfs.Extensions.FileProviders</PackageId>
    <PackageDescription>This is a file provider for HDFS through WebHDFS protocol for Microsoft.Extensions.FileProviders.</PackageDescription>
    <PackageTags>hdfs webhdfs fileprovider filesystem</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <Target Name="SetPackageReleaseNotes" BeforeTargets="GenerateNuspec">
    <ReadLinesFromFile File="$(MSBuildProjectDirectory)\ReleaseNotes.md">
      <Output TaskParameter="Lines" ItemName="ReleaseNotesLines" />
    </ReadLinesFromFile>
    <PropertyGroup>
      <PackageReleaseNotes>@(ReleaseNotesLines, '%0A')</PackageReleaseNotes>
    </PropertyGroup>
  </Target>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="ReleaseNotes.md" />
  </ItemGroup>

</Project>
