[project]
name = "hcoona-one-python"
version = "0.0.0-dev"
description = "This is the root mono-repository for HCOONa's One Python project."
authors = [
    { name = "Shuai Zhang", email = "zhangshuai.ustc@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.12"
license = "GPL-3.0-or-later"
classifiers = ["Private :: Do Not Upload"]

[dependency-groups]
dev = [
    "pyrefly>=0.25.0",
    "pyright>=1.1.400",
    "ruff>=0.11.8",
]

[tool.uv.workspace]
members = [
    "labs/*",
    "packages/*"
]

[tool.uv.sources]
azure-document-intelligence-lab = { workspace = true }

chrome-mcp-client = { workspace = true }
git-commit-heatmap = { workspace = true }
html-sm-processor = { workspace = true }
llm-text-splitter = { workspace = true }
music-flash-card-generator = { workspace = true }
rag-postgresql-openai = { workspace = true }
summarize-edge-tab = { workspace = true }
supermemo-mcp = { workspace = true }
transcribe = { workspace = true }
windows-app-mcp = { workspace = true }
nbgv-python = { workspace = true }

[tool.pyrefly]
project-includes = [
    # "labs/**",
    "packages/**",
]
project-excludes = [
    '.venv/**',
    'dist/**',
]
